apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: otel-collector
  endpoints:
    - port: prometheus
      interval: 15s
      path: /metrics